version: '3.5'

services:
  db_user:
    container_name: db_user
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
    image: postgres:14.3-alpine